# [build]  
#   publish = "build/"
#   command = "cd frontend && npm install && npm run build"

# The following redirect is intended for use with most SPAs 
# that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200